### PR TITLE
Fix ValueErrors raised when numpy iterables use `==` in failed 

### LINKED ISSUE #40: ValueError raised when comparing numpy / pandas iterables
## Context

Given a small test that uses a numpy `array`, working in a clean Python 3.11 virtual environment:

```sh
pip install pytest numpy
cat > test.py
```

```py
import numpy as np

def test() -> None:
    stuff = np.array([1, 2, 3])

    assert all(stuff == 1)
```

`^d`

Test fails as expected.

```sh
pytest test.py
```

Error output from Pytest is clear (just `test`'s failure block shown):

```
_________________________________________________ test __________________________________________________

    def test() -> None:
        stuff = np.array([1, 2, 3])

>       assert all(stuff == 1)
E       assert False
E        +  where False = all(array([1, 2, 3]) == 1)

test.py:6: AssertionError
```

## Current behaviour

When `pytest-icdiff` is installed and tests run, then an error is shown when the test fails because a `ValueError` is raised.

```sh
pip install pytest-icdiff
pytest test.py
```

```
_________________________________________________ test __________________________________________________

    def test() -> None:
        stuff = np.array([1, 2, 3])

>       assert all(stuff == 1)

test.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv311/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:491: in _call_reprcompare
    custom = util._reprcompare(ops[i], each_obj[i], each_obj[i + 1])
venv311/lib/python3.11/site-packages/_pytest/assertion/__init__.py:141: in callbinrepr
    hook_result = ihook.pytest_assertrepr_compare(
venv311/lib/python3.11/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
venv311/lib/python3.11/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

config = <_pytest.config.Config object at 0x7fddd1908450>, op = '==', left = array([1, 2, 3]), right = 1

    def pytest_assertrepr_compare(config, op, left, right):
        if op != "==":
            return

        try:
>           if abs(left + right) < 19999:
E           ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

venv311/lib/python3.11/site-packages/pytest_icdiff.py:22: ValueError
```

This is happening because the `+`, `abs` and `>` operations in `abs(left + right) < 19999` do not result in a single value. Instead they are propagated across the array, yielding a new array:

```py
In [1]: import numpy as np

In [2]: left = np.array([1, 2, 3])

In [3]: right = 1

In [4]: left + right
Out[4]: array([2, 3, 4])

In [5]: abs(left + right) > 19999
Out[5]: array([False, False, False])
```

Numpy then warns the user if an Array of `bool` is treated as a `bool`:

```py
In [6]: bool(_)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 bool(_)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

## Expected behaviour

With `pytest-icdiff` installed, the original `assert False where False = all(array([1, 2, 3]) == 1)` test failure is shown - no `ValueError` is raised.

### PR DESCRIPTION
**Pull request by jamescooke**
## Adds

* `FakeNumpyArray` which emulates enough behaviour at test time to have `all(result == 1)` produce `False` and `abs(left + right) < 19999` raise a `ValueError`. I couldn't find an easy way to do this with `unittest.mock` - but would happily see more elegant solutions. Have built out full tests on this fake.
* Handler for `ValueError` which returns from `pytest_assertrepr_compare()` when a `ValueError` is raised - this allows numpy / pandas iterables to fall-back to default pytest output. Fixes #40 👈🏻 Some design decisions here.

### CODE REVIEW

**Comment by hjwp** [comment]
wow james, this is awesome.  particularly enjoyed the `FakeNumpyArray` :-D

But i think probably even that is too much to carry around (even if it is lighter than a dependency on numpy).

What do you think about just having numpy as an _optional_ dependency of the tests? We can install it for CI I reckon, and then just do a pytest skip if we find it's not installed on any given developer's machine.

maybe just a try/except around "import numpy" would do it.  there's an example here https://stackoverflow.com/a/38442948/366221

**Comment by jamescooke** [comment]
@hjwp How's that looking now?

**Comment by hjwp** [comment]
let's do it!

**Comment by hjwp** [comment]
released as v 0.8.

thanks so much!

**Pull request merged**
